name: Test & deploy model

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                python-version: '3.12'
            - name: Run api unitary tests
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install -r api/requirements.txt
                cd api
                pytest
            - name: Build api image
              run: |
                docker build -t scoring-model-api .
                docker save -o scoring-model-api.tar scoring-model-api
                ls
