name: Test & deploy model

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                python-version: '3.12'
            - name: Run unitary tests
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install -r api/requirements.txt
                cd api
                pytest
            - name: Build image
              run: |
                docker build -t scoring-model-api .
                docker save -o scoring-model-api.tar scoring-model-api
            - name: Copy image to EC2
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ubuntu
                key: ${{ secrets.EC2_SSH_KEY }}
                source: "./scoring-model-api.tar"
                target: "/home/ubuntu"
            - name: Configure and run image on EC2
              uses: appleboy/ssh-action@v1.2.5
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ubuntu
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    sudo apt update && sudo apt upgrade -y && sudo apt install -y docker.io
                    cd ~
                    docker load -i scoring-model-api.tar
                    docker run -d -p 8084:8084 --name scoring-model-container scoring-model-api
