name: Test deploy with Actions

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Build image
              run: |
                docker build -t scoring-model-api .
                docker save -o scoring-model-api.tar scoring-model-api
            - name: Copy image to EC2
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ubuntu
                key: ${{ secrets.EC2_SSH_KEY }}
                source: "./scoring-model-api.tar"
                target: "/home/ubuntu"
            - name: Configure EC2
              uses: appleboy/ssh-action@v1.2.5
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ubuntu
                key: ${{ secrets.EC2_SSH_KEY }}
                command_timeout: 15m
                script: |
                    ls
                    sudo apt update && sudo apt install -y docker.io
                    sudo usermod -aG docker ubuntu
                    sudo systemctl restart docker
                    docker load -i scoring-model-api.tar
